name: Build and Deploy Angular

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: atharvamaheshwari09/angular-app
  TAG: ${{ github.sha }}

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$TAG .
          docker images

      - name: Push Docker Image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$TAG

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Debug Secrets
        run: |
          echo "Checking GitHub Secrets..."

          echo "EC2_USER:"
          if [ -z "${{ secrets.EC2_USER }}" ]; then
            echo "EMPTY"
          else
            echo "EXISTS"
          fi

          echo "EC2_HOST:"
          if [ -z "${{ secrets.EC2_HOST }}" ]; then
            echo "EMPTY"
          else
            echo "EXISTS"
          fi

          echo "EC2_SSH_KEY:"
          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
            echo "EMPTY"
          else
            echo "EXISTS"
          fi

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

          docker pull $REGISTRY/$IMAGE_NAME:$TAG

          docker stop angular-app || true
          docker rm angular-app || true

          docker run -d \
            --name angular-app \
            --restart unless-stopped \
            -p 80:80 \
            $REGISTRY/$IMAGE_NAME:$TAG

          docker ps
          docker images

          EOF